# Generated by Django 5.0.4 on 2024-05-14 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_review_email_review_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_sale',
            field=models.IntegerField(default=0),
        ),
    ]
