# Generated by Django 5.0.4 on 2024-05-16 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_region_customer_order_orderproduct_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
